eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
               defaultZone: http://localhost:8555/eureka
  datacenter: Colombo-SriLanka
  environment: production
server:
  port: 8555

